base:
  api_key: "xxxxx"
  admins: []
  disabled: []
  disabled_monitors: []
  disabled_schedules: []
  disabled_modules: []

command.wolfram:
  api_key: "xxxxx"

command.movie:
  api_key: "xxxxx"

command.translate:
  api_key: "xxxxx"

command.randomaww:
  client_id: "xxxxx"
  client_secret: "xxxxx"
  user_agent: "xxxxx"

command.markov:
  folder: "xxxxx"

command.weather:
  api_key: "xxxxx"

command.populartimes:
  api_key: "xxxxx"

command.rss:
  data_dir: "xxxxx"

command.todayfact:
  datfile: "xxxxx"
